import type { ArtWork } from '@/services/types'

export const ARTWORKS: ArtWork[] = [
  {
    id:          1,
    title:       'Fractured Light',
    medium:      'Digital Oil Painting',
    year:        '2024',
    description: 'A study in how light fractures through polarised glass — each shard carrying a different frequency of truth. Created entirely with custom pressure-sensitive brushes.',
    dimensions:  '4000 × 5000 px',
    colors:      { h1: '#FF6B9D', h2: '#c23070' },
    shape:       'blob1',
    available:   true,
  },
  {
    id:          2,
    title:       'Velocity',
    medium:      '3D CGI Render',
    year:        '2024',
    description: 'Motion captured and distorted — the feeling of moving so fast that your past self becomes a blurred afterimage. Rendered in Blender with custom HDRI lighting.',
    dimensions:  '6000 × 4000 px',
    colors:      { h1: '#FF9F45', h2: '#c96800' },
    shape:       'diamond',
    available:   false,
  },
  {
    id:          3,
    title:       'Synaptic Web',
    medium:      'Mixed Media',
    year:        '2024',
    description: 'Neural pathways mapped onto physical canvas using UV-reactive ink, thread and hand-drawn elements. The mind\'s architecture made tangible.',
    dimensions:  '120 × 90 cm (original)',
    colors:      { h1: '#8B72F0', h2: '#4d28c7' },
    shape:       'blob2',
    available:   true,
  },
  {
    id:          4,
    title:       'Bloom State',
    medium:      'Watercolour',
    year:        '2023',
    description: 'Painted across 14 consecutive mornings — each session adding one layer. The cumulative effect of tiny daily acts of creation. 300gsm cold press paper.',
    dimensions:  '56 × 76 cm (original)',
    colors:      { h1: '#4FC3F7', h2: '#0e7aad' },
    shape:       'circle',
    available:   true,
  },
  {
    id:          5,
    title:       'Urban Decay',
    medium:      'Photography + Digital',
    year:        '2023',
    description: 'Long-exposure photography of abandoned industrial zones, composited with generative texture layers. Beauty found in entropy and structural collapse.',
    dimensions:  'Print series, 5 editions',
    colors:      { h1: '#A8E063', h2: '#5a9e10' },
    shape:       'hexagon',
    available:   false,
  },
  {
    id:          6,
    title:       'Inner Cosmos',
    medium:      'Generative Art',
    year:        '2023',
    description: 'Fully procedural artwork generated through custom GLSL shaders and particle physics simulations. Each render is unique — this is edition 1 of an infinite series.',
    dimensions:  '8000 × 8000 px',
    colors:      { h1: '#F7DC6F', h2: '#c4a200' },
    shape:       'blob1',
    available:   true,
  },
  {
    id:          7,
    title:       'Threshold',
    medium:      'Ink on Paper',
    year:        '2022',
    description: 'A 3-month meditation on doorways — physical, psychological and spiritual. Drawn with technical pens at 0.1mm, 120+ hours of work compressed into one composition.',
    dimensions:  '42 × 59 cm (original)',
    colors:      { h1: '#E8D5B7', h2: '#8B6914' },
    shape:       'triangle',
    available:   false,
  },
  {
    id:          8,
    title:       'Chromatic Memory',
    medium:      'Digital Collage',
    year:        '2022',
    description: 'Memories reconstructed in chromatic fragments — each colour temperature corresponding to an emotional register. Nostalgia visualised as colour temperature drift.',
    dimensions:  '3840 × 2160 px',
    colors:      { h1: '#F48FB1', h2: '#ad1457' },
    shape:       'blob2',
    available:   true,
  },
  {
    id:          9,
    title:       'Deep Signal',
    medium:      'Algorithmic Painting',
    year:        '2021',
    description: 'Audio waveform data from field recordings in the Lagos waterfront, translated into brushstroke vectors by a custom Processing algorithm. Sound made visible.',
    dimensions:  '5000 × 3000 px',
    colors:      { h1: '#80DEEA', h2: '#00838f' },
    shape:       'diamond',
    available:   false,
  },
  {
    id:          10,
    title:       'Origin Point',
    medium:      'Oil on Canvas',
    year:        '2021',
    description: 'The first major oil painting after switching from digital — an intentional return to the physical. The learning, the struggle and the eventual surrender are all visible in the surface.',
    dimensions:  '100 × 120 cm (original)',
    colors:      { h1: '#CE93D8', h2: '#7b1fa2' },
    shape:       'blob1',
    available:   true,
  },
]
