import type { ArtWork } from '@/services/types'

export const ARTWORKS: ArtWork[] = [
  {
    id:          1,
    title:       'The Hollow Crown',
    medium:      'Charcoal on Paper',
    year:        '2024',
    description: 'A skull rendered in heavy charcoal — the only crown every man eventually wears. Drawn in a single sitting, with the cracks left raw to mark the weight of the thing.',
    dimensions:  'A4 sketchbook',
    colors:      { h1: '#FF6B9D', h2: '#c23070' },
    shape:       'blob1',
    available:   true,
    image:       '/assets/art-01.jpeg',
  },
  {
    id:          2,
    title:       'Inheritance of Madness',
    medium:      'Graphite & Charcoal',
    year:        '2025',
    description: 'A man caught mid-snarl, his demons digging into him, trying to keep him back. The piece sits with the question of how much of our rage we actually chose, and how much was handed down.',
    dimensions:  'A4 sketchbook',
    colors:      { h1: '#FF9F45', h2: '#c96800' },
    shape:       'diamond',
    available:   false,
    image:       '/assets/art-02.jpeg',
  },
  {
    id:          3,
    title:       'Severance',
    medium:      'Graphite on Paper',
    year:        '2024',
    description: 'A face sliced into clean horizontal bands — eyes, nose and mouth drifting apart as if the person inside finally gave up holding them together. A study in quiet disassembly.',
    dimensions:  'A3 sketchbook',
    colors:      { h1: '#8B72F0', h2: '#4d28c7' },
    shape:       'blob2',
    available:   true,
    image:       '/assets/art-03.jpeg',
  },
  {
    id:          4,
    title:       'Last Breath',
    medium:      'Charcoal on Paper',
    year:        '2024',
    description: 'A head tipped back, lips parted, a hand resting at the jaw — the precise moment between holding on and letting go. Rendered loose, almost smudged, because grief never draws clean lines.',
    dimensions:  'A4 sketchbook',
    colors:      { h1: '#4FC3F7', h2: '#0e7aad' },
    shape:       'circle',
    available:   true,
    image:       '/assets/art-04.jpeg',
  },
  {
    id:          5,
    title:       'Unmade',
    medium:      'Charcoal on Paper',
    year:        '2023',
    description: 'A scream caught at full volume, the face dissolving into the dark behind it. Drawn quickly, almost violently — the mark-making had to match the noise.',
    dimensions:  'A3 sketchbook',
    colors:      { h1: '#A8E063', h2: '#5a9e10' },
    shape:       'hexagon',
    available:   false,
    image:       '/assets/art-05.jpeg',
  },
  {
    id:          6,
    title:       'In the Palm of Ruin',
    medium:      'Graphite on Paper',
    year:        '2023',
    description: 'A small figure pinched between giant fingers, lifted toward an open mouth. A meditation on the appetites that shape us — and the ones we feed without ever realising we are the meal.',
    dimensions:  'A3 sketchbook',
    colors:      { h1: '#F7DC6F', h2: '#c4a200' },
    shape:       'blob1',
    available:   true,
    image:       '/assets/art-06.jpeg',
  },
  {
    id:          7,
    title:       'Held by Nothing',
    medium:      'Charcoal on Paper',
    year:        '2024',
    description: 'A faceless woman folded into her own arms, the only embrace left available to her. The lightning-mark background is meant to read as both static and grief — pick whichever hurts more.',
    dimensions:  'A4 sketchbook',
    colors:      { h1: '#E8D5B7', h2: '#8B6914' },
    shape:       'triangle',
    available:   false,
    image:       '/assets/art-07.jpeg',
  },
  {
    id:          8,
    title:       'What the Mind Leaves Behind',
    medium:      'Charcoal & Wash',
    year:        '2024',
    description: 'A head eroding in long vertical claw-marks, as if memory itself were peeling away from bone. Drawn during a stretch of bad sleep, when the face in the mirror started to feel borrowed.',
    dimensions:  'A3 sketchbook',
    colors:      { h1: '#F48FB1', h2: '#ad1457' },
    shape:       'blob2',
    available:   true,
    image:       '/assets/art-08.jpeg',
  },
  {
    id:          9,
    title:       "Predator's Vigil",
    medium:      'Graphite on Paper',
    year:        '2021',
    description: 'An eagle in profile, the eye sharper than the beak. A study in patience as a form of violence — the kind of stillness that ends with something dying.',
    dimensions:  'A4 sketchbook',
    colors:      { h1: '#80DEEA', h2: '#00838f' },
    shape:       'diamond',
    available:   false,
    image:       '/assets/art-09.jpeg',
  },
  {
    id:          10,
    title:       'The Witness',
    medium:      'Acrylic on Paper',
    year:        '2021',
    description: 'A dark portrait with two unblinking white eyes, painted to feel less like a face and more like something looking back. The first painted piece after a long stretch of pencil work — and it shows in the silence of it.',
    dimensions:  'A3, acrylic',
    colors:      { h1: '#CE93D8', h2: '#7b1fa2' },
    shape:       'blob1',
    available:   true,
    image:       '/assets/art-10.jpeg',
  },
]
